### PR TITLE
Improvements to cloud-image-val

### PR DESCRIPTION
**Pull request by atodorov**
Notes:

CloudX Azure login is failing, job reported PASS:
https://github.com/osbuild/cloud-cleaner/actions/runs/5344222950/jobs/9688345341

CloudX AWS job says `Unable to locate credentials. You can configure credentials by running "aws configure"`, reports PASS:
https://github.com/osbuild/cloud-cleaner/actions/runs/5344222950/jobs/9688345169

Image Builder AWS job says `An error occurred (AuthFailure) when calling the DescribeRegions operation: AWS was not able to validate the provided access credentials`, reports PASS:
https://github.com/osbuild/cloud-cleaner/actions/runs/5344222063/jobs/9688343730

Image Builder vmware job says `/tmp/govc: Post "https://***/rest/com/vmware/cis/session": dial tcp: lookup *** on 127.0.0.11:53: no such host`, reports PASS:
https://github.com/osbuild/cloud-cleaner/actions/runs/5344222063/jobs/9688343356

### CODE REVIEW

**Comment by atodorov** [comment]
Execution for Image Builder - https://github.com/osbuild/cloud-cleaner/actions/runs/5344759134 - AWS & vmware now reporting FAIL

Execution for CloudX - https://github.com/osbuild/cloud-cleaner/actions/runs/5344653811 - AWS & Azure now reporting FAIL

**Comment by atodorov** [comment]
CloudX, Azure - PASS (removed a few items):
https://github.com/osbuild/cloud-cleaner/actions/runs/5347811051/jobs/9696840737

CloudX, AWS - removed a few items but FAILED with unbound variable for `AWS_BUCKET`, which is not used by CloudX:
https://github.com/osbuild/cloud-cleaner/actions/runs/5347811051/jobs/9696840517

CloudX, AWS - PASS:
https://github.com/osbuild/cloud-cleaner/actions/runs/5347864095/jobs/9696967011

**Comment by atodorov** [comment]
Image Builder, vmware job skipped here: https://github.com/osbuild/cloud-cleaner/actions/runs/5354068938

**Comment by atodorov** [comment]
Image Builder, AWS job: https://github.com/osbuild/cloud-cleaner/actions/runs/5354326186/jobs/9711218851

**Review by jrusz — APPROVED** [review]
I'm not sure if we want to have `set -e` in these scripts. If everything is well and cleanups ran will it always exit with 0? I think the initial reason we didn't include it was that we wanted this to be kind of "best effort" cleanup run to remove as much as possible regardless of failures in between, but I suppose this caused the issues we have now go unnoticed... 

I guess let's leave it there and see how it goes

**Review by ondrejbudai — APPROVED** [review]
Looks good. Let's see how this script works with `set -e`, we can always fix it later if it causes some issues.

**Pull request merged**
